# network parameters
NAME: 'resnet3d'

NETWORK:
  N_INITIAL_FILTERS:  6
  NETWORK_DEPTH:  1
  RESIDUAL_BLOCKS_PER_LAYER: 2


# training parameters:
N_MINIBATCH: 1
MINIBATCH_SIZE: 1
SAVE_ITERATION: 500
REPORT_ITERATION: 10
SUMMARY_ITERATION: 1
BASE_LEARNING_RATE:  0.001
TRAINING: True
ITERATIONS: 50

# IO Parameters:
IO:
  TRAIN:
    PROFILE_IO: True
    FILE: './larcv_io_config/3d/dev/event_id/train_io.cfg'
    FILLER: 'TrainIO'
    VERBOSITY: 3
    KEYWORD_DATA:  'main_data'
    KEYWORD_LABEL:
      - 'main_neutrino_label'
      - 'main_proton_label'
      - 'main_chrpion_label'
      - 'main_ntrpion_label'


# General parameters:
LOGDIR: 'log/log_resnet_3d/'
RESTORE: False


