# network parameters
NUM_LABELS: 36
N_INITIAL_FILTERS:  6
NETWORK_DEPTH_PRE_MERGE:  3
NETWORK_DEPTH_POST_MERGE:  3
RESIDUAL_BLOCKS_PER_LAYER: 1
NPLANES: 3

# training parameters:
N_MINIBATCH: 3
MINIBATCH_SIZE: 32
SAVE_ITERATION: 500
REPORT_ITERATION: 10
SUMMARY_ITERATION: 1
BASE_LEARNING_RATE:  0.003
TRAINING: True
ITERATIONS: 5000
BOOST_LOSSES:
    neutrino: 10.0
    proton: 1.0
    chrpion: 1.0
    ntrpion: 1.0
TRAIN_CONFIG:
    FILE: './config_2d/train_io.cfg'
    FILLER: 'TrainIO'
    VERBOSITY: 3
    KEYWORD_DATA:  'main_data'
    KEYWORD_LABEL:
      - 'main_neutrino_label'
      - 'main_proton_label'
      - 'main_chrpion_label'
      - 'main_ntrpion_label'

TEST_CONFIG:
    FILE: './config_2d/test_io.cfg'
    FILLER: 'TestIO'
    VERBOSITY: 3
    KEYWORD_DATA:  'test_data'
    KEYWORD_LABEL:
      - 'test_neutrino_label'
      - 'test_proton_label'
      - 'test_chrpion_label'
      - 'test_ntrpion_label'

# General parameters:
LOGDIR: 'log_resnet_2d/smaller/'
RESTORE: False
GPU: 0
