# network parameters
NAME: 'resnet'

NETWORK:
  N_INITIAL_FILTERS:  6
  NETWORK_DEPTH_PRE_MERGE:  1
  NETWORK_DEPTH_POST_MERGE:  1
  RESIDUAL_BLOCKS_PER_LAYER: 2
  NPLANES: 3
  SHARE_WEIGHTS: true

# training parameters:
N_MINIBATCH: 1
MINIBATCH_SIZE: 2
SAVE_ITERATION: 500
REPORT_ITERATION: 10
SUMMARY_ITERATION: 1
BASE_LEARNING_RATE:  0.001
TRAINING: True
ITERATIONS: 10001


# IO paramters:
IO:
  TRAIN:
    FILE: './larcv_io_config/2d/full/event_id/train_io.cfg'
    FILLER: 'TrainIO'
    VERBOSITY: 3
    KEYWORD_DATA:  'main_data'
    KEYWORD_LABEL:
      - 'main_neutrino_label'
      - 'main_proton_label'
      - 'main_chrpion_label'
      - 'main_ntrpion_label'

  TEST:
    FILE: './larcv_io_config/2d/full/event_id/test_io.cfg'
    FILLER: 'TestIO'
    VERBOSITY: 3
    KEYWORD_DATA:  'test_data'
    KEYWORD_LABEL:
      - 'test_neutrino_label'
      - 'test_proton_label'
      - 'test_chrpion_label'
      - 'test_ntrpion_label'

# General parameters:
LOGDIR: 'log/log_resnet_716/2d_run1'
RESTORE: False
