# network parameters
NAME: 'uresnet3d'

NETWORK:
  N_INITIAL_FILTERS:  2
  NETWORK_DEPTH:  4
  RESIDUAL_BLOCKS_PER_LAYER: 1
  BALANCE_LOSS: True
  BATCH_NORM: True

# training parameters:
N_MINIBATCH: 1
MINIBATCH_SIZE: 1
SAVE_ITERATION: 500
REPORT_ITERATION: 10
SUMMARY_ITERATION: 1
BASE_LEARNING_RATE:  0.001
TRAINING: True
ITERATIONS: 5

# IO Parameters:
IO:
  TRAIN:
    FILE: './larcv_io_config/3d/dev/lepton_seg/train_io.cfg'
    FILLER: 'TrainIO'
    VERBOSITY: 3
    KEYWORD_DATA:  'main_data'
    KEYWORD_LABEL: 'main_label'

# General parameters:
LOGDIR: 'log/log_uresnet_3d/'
RESTORE: False


